### ISSUE TITLE
Graphic issue #2 

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#327] opened 2019-12-07 08:27 UTC
location : introduction screen
description : The yellow marker does not disappear, it moves along the direction of the root key.
![image](https://user-images.githubusercontent.com/56066524/70371469-62b25880-18f9-11ea-9eb8-f3751fc6bffe.png)

**Comment by SilasReinagel** [comment] 2019-12-07 23:14
Duplicate of #326

**Closed by SilasReinagel** 2019-12-07 23:14 UTC
