### ISSUE TITLE
reset button glitch 

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#329] opened 2019-12-07 08:31 UTC
location : level 3,4,5..
description : reset level animation on levels glitches out , sometimes plays only a couple frames
and sometimes nothing.

**Comment by SilasReinagel** [comment] 2019-12-07 23:11
This is a duplicate of existing open bug EnigmaDragons/ProjectBitVault#304

**Closed by SilasReinagel** 2019-12-07 23:11 UTC
