### ISSUE TITLE
Unproportional lines at the back of character (screenshot)

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#354] opened 2019-12-10 08:24 UTC
![#bug11](https://user-images.githubusercontent.com/56066524/70508472-91ba0b80-1b3f-11ea-8421-8efa91d53325.PNG)
The lines at the back of the character is not proportional and doesn't look professional

**Comment by SilasReinagel** [comment] 2019-12-10 19:04
This is a duplicate of EnigmaDragons/ProjectBitVault#324

**Closed by SilasReinagel** 2019-12-10 19:04 UTC
