### ISSUE TITLE
Home Ui suggestion

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/ProjectBitVault#412] opened 2020-01-02 17:17 UTC
Have a tablet like the player is holding instead of just having the options , shorten the game title a little and move it up so the tablet is bigger and nothing looks cramped. have a box highlighted when the mouse hovers over one of the selection options like play.

**Comment by SilasReinagel** [comment] 2020-01-03 21:25
I don't understand this suggestion. Can you highlight elements on a screenshot?

**Comment by SilasReinagel** [comment] 2020-01-04 21:15
Duplicate of EnigmaDragons/ProjectBitVault#414

**Closed by SilasReinagel** 2020-01-04 21:15 UTC
Labels: duplicate
